### ISSUE TITLE
About the model weight

### ISSUE THREAD

**Issue by AoqunJin** [tinnerhrhe/VPDD#1]
Any open source plan for the VPDD checkpoints? 🤗

**Comment by tinnerhrhe** [comment]
Sure, I will open-source the pre-trained VAE and discrete diffusion model weights since the pre-training is time-consuming and expensive. I will update the repo (e.g., instructions, datasets, and checkpoints) around 11.20. Thanks for your attention!

**Comment by AoqunJin** [comment]
Thanks, that helps a lot.🌹🌹🌹🌹
